### PR TITLE
create form with input elements

### PR DESCRIPTION
**Pull request by rida-elbahtouri**
<h1>PROJECT: HTML FORMS</h1>
**in this project we **:

- Created a blank HTML document.

- Planned out how the elements on the page need to be grouped together.

- Layout the empty semantic HTML elements for the major sections (form, sidebar, footer…) and make them the proper size and alignment. 

- Change their background colors while positioning them on the page. 

- Styled them to look like the real webpage.

- Created an HTML form

### CODE REVIEW

**Comment by Alaska01** [comment]
<h1>HTML Forms</h1>
**On this project we**
created a sign up form

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes :recycle: :traffic_light: 

Hi @rida-elbahtouri and @Alaska01, great work with your project, it looks amazing :smile: Just a few touches and we are good to go :airplane: .Kindly find comments below:
- Kindly add a description to the README file
- Kindly fix the error and warning returned by the w3validator
ww
- Kindly enable stickler for the repo by visiting stickler-ci.com
- Kindly edit the PR and provide a more detailed description of the project. You can copy the project details on the Odin project
- Let us avoid the use of ```ids``` for styling and also apply the DRY rule. Kindly read this [article](https://speckyboy.com/good-bad-css-practices/)
- Let us improve semantics by using ```<section>, <main>, <aside>``` etc

Kindly make these changes and submit another code review :+1: 
_Happy coding_ :man_technologist: 
Daniel Larbi Addo on slack

**Comment by santiago-dev96** [comment]
## Pull Request under review by @santiago-rodrig (TSE)

**Review by santiago-dev96 — CHANGES_REQUESTED** [review]
# Changes required
I can't review this project because it is not a professional PR.

Friendly reminder: You should make sure that your repo looks professional before review.
Please take a step back and read a lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there). This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

**Comment by lekegitrepo** [comment]
#### Hi @rida-elbahtouri and @Alaska01 :clap: :clap:
#### Good job for implementing most of the required changes listed in the previous review.
#### You have not fixed the error mentioned by the previous TSE :point_down: 

Screenshot from 2020-05-06 17-32-08

#### Optional:
**_You can improve the Html semantic structure of the page: you can put the nav inside the header. The basic Html semantic structure is: `<header> </header>   <main> </main>   <footer> </footer>`_**

**_Fix this and submit for review._**

### **_Reviewed by Temitayo Adeleke_**

- Github: [@lekegitrepo](https://github.com/lekegitrepo)
- Twitter: [@leketemi](https://twitter.com/leketemi)
- Linkedin: [linkedin](https://www.linkedin.com/in/temitayo-adeleke/)

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Pull request merged**
